# COMP90024 Cluster and Cloud Computing
# Assignment 2, Semester 1 2020
# City Analytics on the Cloud
# Team 7
# Kurniawan Lastanto - 1114056 - Melbourne
# Mochammad Chaerudin - 1041681 - Melbourne
# Devin Nanayakkara - 1132751 - Melbourne
# Abhishek Anand - 1005884 - Melbourne
# Shaik Anisuzzaman - 1060370 - Melbourne
#


- name: Insert/Update "proxy setting" in /etc/environment
  become: yes
  become_user: root
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
      http_proxy: http://wwwproxy.unimelb.edu.au:8000/
      https_proxy: http://wwwproxy.unimelb.edu.au:8000/
      No_proxy: http://wwwproxy.unimelb.edu.au:8000/

- name: Reboot VM that might have lots of updates to apply
  become: yes
  reboot:
    reboot_timeout: 3600
