# COMP90024 Cluster and Cloud Computing
# Assignment 2, Semester 1 2020
# City Analytics on the Cloud
# Team 7
# Kurniawan Lastanto - 1114056 - Melbourne
# Mochammad Chaerudin - 1041681 - Melbourne
# Devin Nanayakkara - 1132751 - Melbourne
# Abhishek Anand - 1005884 - Melbourne
# Shaik Anisuzzaman - 1060370 - Melbourne
#


- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

- name: Clone harvester git repo
  git:
    repo: https://github.com/dvn14/CCC2020-Group7.git
    dest: /home/ubuntu/CCC2020-Group7
    accept_hostkey: yes

- name: Install harvester packages
  become: yes
  pip:
    requirements: /home/ubuntu/CCC2020-Group7/twitter-harvester/packages.txt

- name: start stream harvester
  shell: nohup python3 ~/CCC2020-Group7/twitter-harvester/twitter-stream.py &

- name: start search harvester
  shell: nohup python3 ~/CCC2020-Group7/twitter-harvester/twitter-search.py &