# COMP90024 Cluster and Cloud Computing
# Assignment 2, Semester 1 2020
# City Analytics on the Cloud
# Team 7
# Kurniawan Lastanto - 1114056 - Melbourne
# Mochammad Chaerudin - 1041681 - Melbourne
# Devin Nanayakkara - 1132751 - Melbourne
# Abhishek Anand - 1005884 - Melbourne
# Shaik Anisuzzaman - 1060370 - Melbourne
#


- name: Clone couchDB git repo
  become: yes
  git:
    repo: https://github.com/redgeoff/docker-ce-vagrant
    dest: /home/ubuntu/docker-ce-vagrant
    accept_hostkey: yes

- name: run shell commands for docker and ubuntu
  become: yes
  become_user: root 
  shell: |
    cd docker-ce-vagrant
    sudo ./ubuntu.sh
    sudo ./docker.sh
    

- name: Create a directory for hosting  DB files
  become: yes
  file:
    path: /home/ubuntu/common
    state: directory
    mode: 0755

- name: Run a CouchDB Docker Container
  become: yes
  become_user: root
  command: sudo docker run -d --name couchdb --log-opt max-size=100m --restart always -p 5984:5984  -p 5986:5986 -p 4369:4369 -p 9100-9200:9100-9200 -v /home/ubuntu/common/data:/opt/couchdb/data -e COUCHDB_USER='admin' -e COUCHDB_PASSWORD='-pbkdf2-b1eb7a68b0778a529c68d30749954e9e430417fb,4da0f8f1d98ce649a9c5a3845241ae24,10' -e COUCHDB_SECRET='mysecret' -e NODENAME='{{ansible_default_ipv4.address}}' couchdb -setcookie mycookie

- name: Curl command
  become: yes
  become_user: root
  shell: curl -sL https://deb.nodesource.com/setup_8.x
  args:
    warn: no

#- name: Install nodejs build-essential
#  become: yes
#  become_user: root
# apt:
#    name: nodejs
#    state: present

#- name: Install npm 
#  become: yes
#  become_user: root
#  apt:
#    name: npm
#    state: present


#- name: install core
#  become: yes
#  become_user: root
#  shell: sudo npm install -g add-cors-to-couchdb
  
#- name: setting up user name and password
#  become: yes
#  command: add-cors-to-couchdb http://localhost:5984 -u admin -p admin

    
