# COMP90024 Cluster and Cloud Computing
# Assignment 2, Semester 1 2020
# City Analytics on the Cloud
# Team 7
# Kurniawan Lastanto - 1114056 - Melbourne
# Mochammad Chaerudin - 1041681 - Melbourne
# Devin Nanayakkara - 1132751 - Melbourne
# Abhishek Anand - 1005884 - Melbourne
# Shaik Anisuzzaman - 1060370 - Melbourne
#


---
- hosts: localhost
  vars_files:
    - host_vars/variables.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
 

- hosts: HOSTS
  vars_files:
    - host_vars/docker_vars.yaml
  gather_facts: true

  roles:
    - role: wp-common
    - role: wp-volumes
    - role: wp-docker
    - role: openstack-proxy


- hosts: WEBHOSTS
  vars_files:
    - host_vars/docker_vars.yaml
  gather_facts: true

  roles:
    - role: wp-common
    - role: wp-volumes
    - role: wp-docker
    - role: openstack-proxy

- hosts: HOSTS
  gather_facts: true

  roles:
    - role: launch-couchdb
    - role: twitter-harvester

